using System.Globalization;

namespace FabClassifiedAds.Web.Services;

/// <summary>
/// Lightweight dictionary translator. Romanian is the primary language; any key
/// missing from the dictionaries falls back to the key itself (English source text).
/// </summary>
public class Translator
{
    public static bool IsRo => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ro";

    public string this[string key] =>
        IsRo && Ro.TryGetValue(key, out var ro) ? ro
        : En.TryGetValue(key, out var en) ? en
        : key;

    public string Format(string key, params object[] args) => string.Format(this[key], args);

    /// <summary>English texts for sentence keys that contain placeholders.</summary>
    private static readonly Dictionary<string, string> En = new()
    {
        ["HeroSubtitle"] = "{0} live ads across {1} categories — cars, homes, tech and more.",
        ["EuroOrNewer"] = "Euro {0} or newer",
        ["CountSelected"] = "{0} selected",
        ["CountSubcategories"] = "{0} subcategories",
        ["PhotoLimits"] = "(up to 10, max 5 MB each — JPEG, PNG, WebP, GIF)",
        ["ResultsFor"] = "Results for “{0}”",
        ["VideoLimits"] = "(optional — MP4/WebM/MOV, max 60 MB)",
        ["PriceBelowMarket"] = "Price is {0}% below the market median ({1} similar ads) — possible risk",
        ["PriceFair"] = "Fair price for this market ({0} similar ads)",
        ["PriceVsMarket"] = "Price is {0}% vs the market median ({1} similar ads)",
    };

    private static readonly Dictionary<string, string> Ro = new()
    {
        // sentence keys
        ["HeroSubtitle"] = "{0} anunțuri active în {1} categorii — mașini, locuințe, electronice și altele.",
        ["EuroOrNewer"] = "Euro {0} sau mai nou",
        ["CountSelected"] = "{0} selectate",
        ["CountSubcategories"] = "{0} subcategorii",
        ["PhotoLimits"] = "(maxim 10, câte 5 MB fiecare — JPEG, PNG, WebP, GIF)",
        ["ResultsFor"] = "Rezultate pentru „{0}”",
        ["VideoLimits"] = "(opțional — MP4/WebM/MOV, maxim 60 MB)",

        // feed & sharing
        ["Video"] = "Video",
        ["Add a vertical video — video ads appear first in the FabFeed"] =
            "Adaugă un video vertical — anunțurile cu video apar primele în FabFeed",
        ["Swipe or scroll"] = "Glisează sau derulează",
        ["Share"] = "Distribuie",
        ["Share link"] = "Distribuie linkul",
        ["Share card"] = "Card de share",
        ["Post the 9:16 card straight to TikTok or Instagram stories."] =
            "Postează cardul 9:16 direct pe TikTok sau Instagram stories.",
        ["Link copied"] = "Link copiat",

        // trust engine
        ["PriceBelowMarket"] = "Preț cu {0}% sub media pieței ({1} anunțuri similare) — posibil risc",
        ["PriceFair"] = "Preț corect pentru piață ({0} anunțuri similare)",
        ["PriceVsMarket"] = "Preț cu {0}% față de media pieței ({1} anunțuri similare)",
        ["FabAds verification"] = "Verificare FabAds",
        ["Trust score"] = "Scor de încredere",
        ["Trusted listing"] = "Anunț de încredere",
        ["Caution advised"] = "Atenție recomandată",
        ["High risk"] = "Risc ridicat — evită",
        ["Trusted seller"] = "Vânzător sigur",
        ["Avoid this seller"] = "Evită acest vânzător",
        ["Risky language detected"] = "Limbaj riscant detectat",
        ["Link in description"] = "Link în descriere",
        ["Phone number in title"] = "Număr de telefon în titlu",
        ["ALL CAPS title"] = "Titlu scris cu MAJUSCULE",
        ["Very short description"] = "Descriere foarte scurtă — lipsesc detaliile",
        ["Detailed description"] = "Descriere detaliată",
        ["Duplicate description (copy/paste)"] = "Descriere duplicată (copy/paste)",
        ["Has video"] = "Are video",
        ["Real photos uploaded"] = "Fotografii reale încărcate",
        ["Generic images only"] = "Doar imagini generice",
        ["Price far below market"] = "Preț anormal de mic",
        ["Price below market"] = "Preț sub media pieței",
        ["Realistic price for this market"] = "Preț realist pentru piață",
        ["New account"] = "Cont nou-creat",
        ["Recent account"] = "Cont recent",
        ["Established account"] = "Cont cu vechime",
        ["Email confirmed"] = "Email confirmat",
        ["Email not confirmed"] = "Email neconfirmat",
        ["Good ratings"] = "Recenzii bune",
        ["Low ratings"] = "Recenzii slabe",
        ["No ratings yet"] = "Fără recenzii încă",
        ["Risky messages sent"] = "Trimite mesaje riscante în chat",
        ["Some risky messages sent"] = "Câteva mesaje riscante în chat",
        ["Responds quickly"] = "Răspunde rapid",
        ["Business account"] = "Cont de firmă",
        ["Flag.AdvancePayment"] = "Acest mesaj cere avans — risc ridicat de înșelăciune. Nu plăti niciodată înainte să vezi produsul!",
        ["Flag.SuspiciousLink"] = "Link detectat — posibil phishing. Nu accesa link-uri primite de la necunoscuți.",
        ["Flag.OffPlatform"] = "Încearcă mutarea conversației pe altă platformă — discuțiile din FabAds rămân protejate.",
        ["Flag.UntraceablePayment"] = "Cere plată netrasabilă (transfer extern / crypto / gift card) — risc foarte ridicat.",

        // header & nav
        ["Buy, sell, discover anything"] = "Cumpără, vinde, descoperă orice",
        ["Post ad"] = "Adaugă anunț",
        ["Sign in"] = "Conectare",
        ["Sign out"] = "Deconectare",
        ["Favorites"] = "Favorite",
        ["Messages"] = "Mesaje",
        ["My ads"] = "Anunțurile mele",
        ["Alerts"] = "Alerte",
        ["Search 25,000+ ads — cars, apartments, phones…"] = "Caută în 25.000+ anunțuri — mașini, apartamente, telefoane…",

        // hero & homepage
        ["Find"] = "Găsește",
        ["anything"] = "orice",
        ["Sell"] = "Vinde",
        ["everything"] = "tot",
        ["What are you looking for today?"] = "Ce cauți astăzi?",
        ["All categories"] = "Toate categoriile",
        ["Search"] = "Caută",
        ["Trending:"] = "În tendințe:",
        ["Browse categories"] = "Explorează categoriile",
        ["Every category has tailored filters — engine specs for cars, floor plans for homes."] =
            "Fiecare categorie are filtre dedicate — specificații tehnice la mașini, compartimentare la locuințe.",
        ["Featured ads"] = "Anunțuri promovate",
        ["See all →"] = "Vezi toate →",
        ["Shop cars by brand"] = "Mașini după marcă",
        ["All cars →"] = "Toate mașinile →",
        ["Fresh on FabAds"] = "Noutăți pe FabAds",
        ["Got something to sell?"] = "Ai ceva de vândut?",
        ["Post your ad in under a minute. Free, forever, with smart category-specific forms."] =
            "Publică anunțul în mai puțin de un minut. Gratuit, pentru totdeauna, cu formulare inteligente pe categorii.",
        ["+ Post your ad"] = "+ Adaugă anunțul tău",
        ["Verified sellers"] = "Vânzători verificați",
        ["Ratings and reviews on every account, business badges for dealers."] =
            "Evaluări și recenzii la fiecare cont, insigne de firmă pentru dealeri.",
        ["Surgical filters"] = "Filtre chirurgicale",
        ["Filter cars by engine, power, options. Homes by floor, heating, amenities."] =
            "Filtrează mașinile după motor, putere, dotări. Locuințele după etaj, încălzire, facilități.",
        ["Built-in chat"] = "Chat integrat",
        ["Message sellers instantly without sharing your phone number."] =
            "Scrie vânzătorilor instant, fără să-ți dai numărul de telefon.",
        ["Always fast"] = "Mereu rapid",
        ["Built on .NET 11 — pages render in milliseconds, even on mobile."] =
            "Construit pe .NET 11 — paginile se încarcă în milisecunde, chiar și pe mobil.",
        ["Home"] = "Acasă",

        // search & filters
        ["All ads"] = "Toate anunțurile",
        ["ads"] = "anunțuri",
        ["Map view"] = "Hartă",
        ["Save search"] = "Salvează căutarea",
        ["Price (€)"] = "Preț (€)",
        ["From"] = "De la",
        ["To"] = "Până la",
        ["Location"] = "Locație",
        ["City or region"] = "Oraș sau județ",
        ["Brand & model"] = "Marcă & model",
        ["Any brand"] = "Orice marcă",
        ["Any model"] = "Orice model",
        ["Popular brands"] = "Mărci populare",
        ["All brands"] = "Toate mărcile",
        ["Year"] = "An",
        ["Mileage (km)"] = "Kilometraj (km)",
        ["Fuel"] = "Combustibil",
        ["Any fuel"] = "Orice combustibil",
        ["Transmission & body"] = "Transmisie & caroserie",
        ["Any transmission"] = "Orice transmisie",
        ["Any body type"] = "Orice caroserie",
        ["Any drivetrain"] = "Orice tracțiune",
        ["Engine (cm³)"] = "Motor (cm³)",
        ["Power (hp)"] = "Putere (CP)",
        ["More"] = "Altele",
        ["Color"] = "Culoare",
        ["Any emission standard"] = "Orice normă de poluare",
        ["Accident-free only"] = "Doar fără accidente",
        ["With service book"] = "Cu carte de service",
        ["Equipment & options"] = "Dotări & opțiuni",
        ["Choose options"] = "Alege dotările",
        ["Property"] = "Imobil",
        ["Any property type"] = "Orice tip de imobil",
        ["Buy or rent"] = "Vânzare sau închiriere",
        ["Rooms"] = "Camere",
        ["Surface (m²)"] = "Suprafață (m²)",
        ["Floor"] = "Etaj",
        ["Year built"] = "An construcție",
        ["Heating & furnishing"] = "Încălzire & mobilare",
        ["Any heating"] = "Orice încălzire",
        ["Any furnishing"] = "Orice mobilare",
        ["Amenities"] = "Facilități",
        ["Choose amenities"] = "Alege facilitățile",
        ["Seller & condition"] = "Vânzător & stare",
        ["Any seller"] = "Orice vânzător",
        ["Private"] = "Persoană fizică",
        ["Business"] = "Firmă",
        ["Any condition"] = "Orice stare",
        ["Negotiable only"] = "Doar negociabile",
        ["Apply filters"] = "Aplică filtrele",
        ["Reset all"] = "Resetează tot",
        ["Sort by"] = "Sortează după",
        ["Newest first"] = "Cele mai noi",
        ["Price: low → high"] = "Preț: crescător",
        ["Price: high → low"] = "Preț: descrescător",
        ["Most viewed"] = "Cele mai văzute",
        ["Lowest mileage"] = "Kilometraj minim",
        ["Newest cars"] = "Cele mai noi mașini",
        ["Largest surface"] = "Suprafață maximă",
        ["No ads match your filters"] = "Niciun anunț nu corespunde filtrelor",
        ["Try widening the price range or removing some filters."] =
            "Încearcă să lărgești intervalul de preț sau să elimini câteva filtre.",

        // listing detail
        ["Vehicle specifications"] = "Specificații vehicul",
        ["Brand"] = "Marcă",
        ["Model"] = "Model",
        ["Variant"] = "Versiune",
        ["Mileage"] = "Kilometraj",
        ["Transmission"] = "Transmisie",
        ["Body"] = "Caroserie",
        ["Drivetrain"] = "Tracțiune",
        ["Engine"] = "Motor",
        ["Power"] = "Putere",
        ["Battery"] = "Baterie",
        ["Range"] = "Autonomie",
        ["Doors"] = "Uși",
        ["Emission"] = "Normă poluare",
        ["Consumption"] = "Consum",
        ["Owners"] = "Proprietari",
        ["Accident-free"] = "Fără accidente",
        ["Service book"] = "Carte de service",
        ["Yes"] = "Da",
        ["No"] = "Nu",
        ["Equipment"] = "Dotări",
        ["Property details"] = "Detalii imobil",
        ["Type"] = "Tip",
        ["Transaction"] = "Tranzacție",
        ["Bedrooms"] = "Dormitoare",
        ["Bathrooms"] = "Băi",
        ["Surface"] = "Suprafață",
        ["Land"] = "Teren",
        ["Ground"] = "Parter",
        ["Energy class"] = "Clasă energetică",
        ["Furnished"] = "Mobilare",
        ["Description"] = "Descriere",
        ["Posted"] = "Publicat",
        ["views"] = "vizualizări",
        ["negotiable"] = "negociabil",
        ["metallic"] = "metalizat",
        ["On FabAds since"] = "Pe FabAds din",
        ["reviews"] = "recenzii",
        ["Stay safe"] = "Siguranța ta",
        ["Meet in a public place"] = "Întâlnește-te într-un loc public",
        ["Check the item before paying"] = "Verifică produsul înainte să plătești",
        ["Never pay in advance to strangers"] = "Nu plăti niciodată în avans străinilor",
        ["Send message"] = "Trimite mesaj",
        ["Hi! Is this still available?"] = "Bună! Mai este valabil?",
        ["Saved — remove"] = "Salvat — elimină",
        ["Save to favorites"] = "Salvează la favorite",
        ["Sign in to contact seller"] = "Conectează-te pentru a contacta vânzătorul",
        ["This is your ad."] = "Acesta este anunțul tău.",
        ["Similar ads"] = "Anunțuri similare",
        ["Featured"] = "Promovat",

        // create form
        ["Post your ad"] = "Publică anunțul tău",
        ["Pick the right category to unlock tailored fields — buyers filter by them."] =
            "Alege categoria potrivită ca să deblochezi câmpurile dedicate — cumpărătorii filtrează după ele.",
        ["Category"] = "Categorie",
        ["Choose a category…"] = "Alege o categorie…",
        ["Title"] = "Titlu",
        ["Price"] = "Preț",
        ["Currency"] = "Monedă",
        ["Condition"] = "Stare",
        ["Negotiable"] = "Negociabil",
        ["Give away for free"] = "Ofer gratuit",
        ["Photos"] = "Fotografii",
        ["Click to choose photos"] = "Apasă pentru a alege fotografii",
        ["The first photo becomes the cover"] = "Prima fotografie devine coperta",
        ["City"] = "Oraș",
        ["Region"] = "Județ",
        ["Vehicle details"] = "Detalii vehicul",
        ["Choose brand…"] = "Alege marca…",
        ["Choose model…"] = "Alege modelul…",
        ["Year…"] = "An…",
        ["Fuel…"] = "Combustibil…",
        ["Transmission…"] = "Transmisie…",
        ["Body…"] = "Caroserie…",
        ["Drive…"] = "Tracțiune…",
        ["Type…"] = "Tip…",
        ["Sale / rent…"] = "Vânzare / închiriere…",
        ["Heating…"] = "Încălzire…",
        ["Furnishing…"] = "Mobilare…",
        ["Heating"] = "Încălzire",
        ["Total floors"] = "Etaje total",
        ["Publish ad"] = "Publică anunțul",
        ["e.g. BMW 320d xDrive M Sport, 2021, full options"] = "ex. BMW 320d xDrive M Sport, 2021, full options",
        ["Describe the condition, history and what makes it great…"] =
            "Descrie starea, istoricul și ce îl face special…",
        ["e.g. Bucharest"] = "ex. București",
        ["e.g. Ilfov"] = "ex. Ilfov",
        ["e.g. 320d xDrive M Sport"] = "ex. 320d xDrive M Sport",
        ["e.g. Mineral Grey"] = "ex. Gri mineral",

        // auth
        ["Welcome back 👋"] = "Bine ai revenit 👋",
        ["Sign in to manage your ads, favorites and messages."] =
            "Conectează-te pentru a-ți administra anunțurile, favoritele și mesajele.",
        ["Email"] = "Email",
        ["Password"] = "Parolă",
        ["Keep me signed in"] = "Ține-mă conectat",
        ["New here?"] = "Ești nou aici?",
        ["Create an account"] = "Creează un cont",
        ["Demo account:"] = "Cont demo:",
        ["Join FabAds 🚀"] = "Alătură-te FabAds 🚀",
        ["Free forever. Post unlimited ads."] = "Gratuit pentru totdeauna. Anunțuri nelimitate.",
        ["Display name"] = "Nume afișat",
        ["optional"] = "opțional",
        ["Confirm password"] = "Confirmă parola",
        ["I'm a business / dealer"] = "Sunt firmă / dealer",
        ["Create account"] = "Creează cont",
        ["Already have an account?"] = "Ai deja cont?",

        // favorites / my ads / saved searches / messages / map
        ["No favorites yet"] = "Niciun favorit încă",
        ["Tap the heart on any ad to save it here."] = "Apasă inima de pe orice anunț pentru a-l salva aici.",
        ["+ Post new ad"] = "+ Adaugă anunț nou",
        ["You haven't posted anything yet"] = "Nu ai publicat încă nimic",
        ["Post your first ad"] = "Publică primul tău anunț",
        ["— it takes under a minute."] = "— durează sub un minut.",
        ["Saved searches"] = "Căutări salvate",
        ["We check for new matching ads every couple of minutes and email you about them."] =
            "Verificăm anunțurile noi la fiecare câteva minute și îți trimitem email.",
        ["No saved searches yet"] = "Nicio căutare salvată încă",
        ["Run a search with your favorite filters, then hit"] = "Fă o căutare cu filtrele tale preferate, apoi apasă",
        ["Run"] = "Rulează",
        ["Pause alerts"] = "Oprește alertele",
        ["Resume alerts"] = "Pornește alertele",
        ["Delete"] = "Șterge",
        ["Saved"] = "Salvată",
        ["alerts on"] = "alerte active",
        ["alerts off"] = "alerte oprite",
        ["Select a conversation"] = "Selectează o conversație",
        ["No conversations yet. Message a seller from any ad."] =
            "Nicio conversație încă. Scrie unui vânzător de pe orice anunț.",
        ["Write a message…"] = "Scrie un mesaj…",
        ["Send"] = "Trimite",
        ["on the map"] = "pe hartă",
        ["List view"] = "Listă",
        ["Showing every filtered ad that has a location. Click a marker for details."] =
            "Se afișează toate anunțurile filtrate care au locație. Apasă pe un marker pentru detalii.",

        // footer
        ["Marketplace"] = "Piață",
        ["Account"] = "Cont",
        ["Built with"] = "Construit cu",
        ["The most complete classifieds platform. Buy, sell and discover anything — from cars to castles."] =
            "Cea mai completă platformă de anunțuri. Cumpără, vinde și descoperă orice — de la mașini la castele.",
        ["All rights reserved."] = "Toate drepturile rezervate.",
        ["Cars"] = "Autoturisme",
        ["Real Estate"] = "Imobiliare",
        ["Electronics"] = "Electronice",
        ["Post an ad"] = "Adaugă un anunț",

        // enums — fuel
        ["Petrol"] = "Benzină",
        ["Hybrid"] = "Hibrid",
        ["Plug in hybrid"] = "Hibrid plug-in",
        ["Lpg"] = "GPL",
        ["Cng"] = "GNC",
        ["Hydrogen fuel cell"] = "Hidrogen",
        // enums — transmission
        ["Manual"] = "Manuală",
        ["Automatic"] = "Automată",
        ["Semi automatic"] = "Semiautomată",
        ["Cvt"] = "CVT",
        // enums — body
        ["Sedan"] = "Berlină",
        ["Estate"] = "Break",
        ["Suv"] = "SUV",
        ["Convertible"] = "Cabrio",
        ["Pickup"] = "Pick-up",
        ["Minivan"] = "Monovolum",
        ["Van"] = "Utilitară",
        ["Off road"] = "Off-road",
        // enums — drivetrain
        ["Front wheel"] = "Tracțiune față",
        ["Rear wheel"] = "Tracțiune spate",
        ["All wheel"] = "Integrală 4x4",
        // enums — condition
        ["New"] = "Nou",
        ["Used"] = "Utilizat",
        ["Refurbished"] = "Recondiționat",
        ["For parts"] = "Pentru piese",
        // enums — property
        ["Apartment"] = "Apartament",
        ["House"] = "Casă",
        ["Studio"] = "Garsonieră",
        ["Villa"] = "Vilă",
        ["Commercial"] = "Spațiu comercial",
        ["Office"] = "Birou",
        ["Garage"] = "Garaj",
        ["Room"] = "Cameră",
        ["Warehouse"] = "Depozit",
        ["Building"] = "Clădire",
        ["Sale"] = "Vânzare",
        ["Rent"] = "Închiriere",
        ["Rent short term"] = "Regim hotelier",
        // enums — heating / furnishing
        ["Central"] = "Centrală de bloc",
        ["Own gas boiler"] = "Centrală proprie",
        ["Heat pump"] = "Pompă de căldură",
        ["Wood"] = "Lemne",
        ["District"] = "Termoficare",
        ["Underfloor heating"] = "Încălzire în pardoseală",
        ["Unfurnished"] = "Nemobilat",
        ["Partially furnished"] = "Parțial mobilat",
        ["Luxury furnished"] = "Mobilat lux",
        // enums — car options
        ["Abs"] = "ABS",
        ["Esp"] = "ESP",
        ["Air conditioning"] = "Aer condiționat",
        ["Climate control"] = "Climatronic",
        ["Cruise control"] = "Pilot automat",
        ["Adaptive cruise control"] = "Pilot automat adaptiv",
        ["Heated seats"] = "Scaune încălzite",
        ["Ventilated seats"] = "Scaune ventilate",
        ["Leather interior"] = "Interior piele",
        ["Sunroof"] = "Trapă",
        ["Panoramic roof"] = "Plafon panoramic",
        ["Navigation"] = "Navigație",
        ["Apple car play android auto"] = "Apple CarPlay / Android Auto",
        ["Parking sensors"] = "Senzori de parcare",
        ["Rear camera"] = "Cameră marșarier",
        ["Camera 360"] = "Cameră 360°",
        ["Keyless entry"] = "Acces fără cheie",
        ["Xenon led"] = "Faruri Xenon / LED",
        ["Matrix headlights"] = "Faruri Matrix",
        ["Alloy wheels"] = "Jante de aliaj",
        ["Tow bar"] = "Cârlig de remorcare",
        ["Lane assist"] = "Asistent menținere bandă",
        ["Blind spot monitor"] = "Monitorizare unghi mort",
        ["Head up display"] = "Head-up display",
        ["Electric seats"] = "Scaune electrice",
        ["Memory seats"] = "Scaune cu memorie",
        ["Heated steering wheel"] = "Volan încălzit",
        ["Ambient lighting"] = "Lumini ambientale",
        ["Premium sound"] = "Sistem audio premium",
        ["Wireless charging"] = "Încărcare wireless",
        ["Auto parking"] = "Parcare automată",
        ["Night vision"] = "Vedere nocturnă",
        ["Air suspension"] = "Suspensie pneumatică",
        ["Sport package"] = "Pachet sport",
        ["Winter tires included"] = "Anvelope de iarnă incluse",
        ["Isofix mounts"] = "Prinderi Isofix",
        // enums — amenities
        ["Balcony"] = "Balcon",
        ["Terrace"] = "Terasă",
        ["Garden"] = "Grădină",
        ["Parking spot"] = "Loc de parcare",
        ["Elevator"] = "Lift",
        ["Basement"] = "Subsol",
        ["Storage room"] = "Boxă",
        ["Swimming pool"] = "Piscină",
        ["Sauna"] = "Saună",
        ["Gym"] = "Sală de fitness",
        ["Security 24h"] = "Pază 24h",
        ["Video intercom"] = "Videointerfon",
        ["Alarm"] = "Alarmă",
        ["Smart home"] = "Smart home",
        ["Solar panels"] = "Panouri solare",
        ["Ev charger"] = "Încărcător EV",
        ["Fireplace"] = "Șemineu",
        ["Pets allowed"] = "Animale acceptate",
        ["Wheelchair access"] = "Acces persoane cu dizabilități",
        ["Sea view"] = "Vedere la mare",
        ["Mountain view"] = "Vedere la munte",
        ["Dishwasher"] = "Mașină de spălat vase",
        ["Washing machine"] = "Mașină de spălat rufe",
        ["Cable tv"] = "TV prin cablu",
        ["New building"] = "Construcție nouă",
        ["Renovated"] = "Renovat",

        // categories (roots + common subcategories; the rest fall back to English)
        ["Auto, Moto & Boats"] = "Auto, Moto & Ambarcațiuni",
        ["Electronics & Appliances"] = "Electronice & Electrocasnice",
        ["Home & Garden"] = "Casă & Grădină",
        ["Fashion & Beauty"] = "Modă & Frumusețe",
        ["Mom & Kids"] = "Mamă & Copil",
        ["Sports, Hobby & Leisure"] = "Sport, Hobby & Timp liber",
        ["Animals"] = "Animale",
        ["Agriculture & Industry"] = "Agricultură & Industrie",
        ["Jobs"] = "Locuri de muncă",
        ["Services"] = "Servicii",
        ["Motorcycles"] = "Motociclete",
        ["Trucks & Commercial"] = "Camioane & Utilitare",
        ["Boats & Watercraft"] = "Ambarcațiuni",
        ["Agricultural vehicles"] = "Vehicule agricole",
        ["Construction machinery"] = "Utilaje de construcții",
        ["Auto parts & Accessories"] = "Piese auto & Accesorii",
        ["Tires & Wheels"] = "Anvelope & Jante",
        ["Campers & Caravans"] = "Autorulote & Rulote",
        ["Apartments for sale"] = "Apartamente de vânzare",
        ["Apartments for rent"] = "Apartamente de închiriat",
        ["Houses for sale"] = "Case de vânzare",
        ["Houses for rent"] = "Case de închiriat",
        ["Land & Plots"] = "Terenuri",
        ["Commercial spaces"] = "Spații comerciale",
        ["Offices"] = "Birouri",
        ["Warehouses & Industrial"] = "Depozite & Industrial",
        ["Garages & Parking"] = "Garaje & Parcări",
        ["Rooms for rent / Flatmates"] = "Camere de închiriat / Colegi",
        ["Vacation rentals"] = "Cazare de vacanță",
        ["New developments"] = "Ansambluri noi",
        ["Mobile phones"] = "Telefoane mobile",
        ["Computers & Laptops"] = "Calculatoare & Laptopuri",
        ["Tablets & E-readers"] = "Tablete & E-readere",
        ["TV & Home cinema"] = "TV & Home cinema",
        ["Audio & Hi-Fi"] = "Audio & Hi-Fi",
        ["Photo & Video"] = "Foto & Video",
        ["Gaming & Consoles"] = "Gaming & Console",
        ["Large appliances"] = "Electrocasnice mari",
        ["Small appliances"] = "Electrocasnice mici",
        ["Furniture"] = "Mobilă",
        ["Home decor"] = "Decorațiuni",
        ["Kitchen & Dining"] = "Bucătărie & Dining",
        ["Garden & Terrace"] = "Grădină & Terasă",
        ["Tools & DIY"] = "Scule & Bricolaj",
        ["Construction materials"] = "Materiale de construcții",
        ["Women's clothing"] = "Haine damă",
        ["Men's clothing"] = "Haine bărbați",
        ["Shoes"] = "Încălțăminte",
        ["Bags & Accessories"] = "Genți & Accesorii",
        ["Watches & Jewelry"] = "Ceasuri & Bijuterii",
        ["Beauty & Health"] = "Frumusețe & Sănătate",
        ["Strollers & Car seats"] = "Cărucioare & Scaune auto",
        ["Kids' clothing & Shoes"] = "Haine & Încălțăminte copii",
        ["Toys & Games"] = "Jucării & Jocuri",
        ["Kids' furniture"] = "Mobilier copii",
        ["Baby essentials"] = "Articole bebeluși",
        ["School supplies"] = "Rechizite",
        ["Bicycles"] = "Biciclete",
        ["E-scooters & Mobility"] = "Trotinete electrice",
        ["Fitness & Gym"] = "Fitness & Sală",
        ["Winter sports"] = "Sporturi de iarnă",
        ["Water sports"] = "Sporturi nautice",
        ["Fishing & Hunting"] = "Pescuit & Vânătoare",
        ["Camping & Outdoor"] = "Camping & Outdoor",
        ["Team sports"] = "Sporturi de echipă",
        ["Musical instruments"] = "Instrumente muzicale",
        ["Books, Movies & Music"] = "Cărți, Filme & Muzică",
        ["Collectibles & Art"] = "Colecții & Artă",
        ["Board games & Puzzles"] = "Jocuri de societate & Puzzle",
        ["Tickets & Events"] = "Bilete & Evenimente",
        ["Dogs"] = "Câini",
        ["Cats"] = "Pisici",
        ["Birds"] = "Păsări",
        ["Fish & Aquariums"] = "Pești & Acvarii",
        ["Small animals"] = "Animale mici",
        ["Farm animals"] = "Animale de fermă",
        ["Pet food & Accessories"] = "Hrană & Accesorii animale",
        ["Pet services"] = "Servicii pentru animale",
        ["IT & Software"] = "IT & Software",
        ["Engineering"] = "Inginerie",
        ["Construction & Trades"] = "Construcții & Meserii",
        ["Transport & Logistics"] = "Transport & Logistică",
        ["Retail & Sales"] = "Comerț & Vânzări",
        ["Hospitality & Tourism"] = "HoReCa & Turism",
        ["Healthcare"] = "Sănătate",
        ["Education"] = "Educație",
        ["Finance & Accounting"] = "Finanțe & Contabilitate",
        ["Marketing & PR"] = "Marketing & PR",
        ["Customer support"] = "Suport clienți",
        ["Cleaning & Housekeeping"] = "Curățenie & Menaj",
        ["Beauty & Wellness jobs"] = "Joburi Frumusețe & Wellness",
        ["Agriculture jobs"] = "Joburi în agricultură",
        ["Work abroad"] = "Muncă în străinătate",
        ["Construction & Renovation"] = "Construcții & Renovări",
        ["Electrician & Plumber"] = "Electrician & Instalator",
        ["Moving & Transport"] = "Mutări & Transport",
        ["Auto services"] = "Service auto",
        ["Cleaning services"] = "Servicii de curățenie",
        ["IT & Web services"] = "Servicii IT & Web",
        ["Photo & Video services"] = "Servicii Foto & Video",
        ["Events & Catering"] = "Evenimente & Catering",
        ["Tutoring & Courses"] = "Meditații & Cursuri",
        ["Beauty services"] = "Servicii de înfrumusețare",
        ["Legal & Accounting"] = "Juridic & Contabilitate",
        ["Repair services"] = "Reparații",
    };
}
